### ISSUE TITLE
[PE-D][Tester D] Attendance not marked as intended (Date)

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T09-1/tp#162]
Test command:
- `student 1B attendance in/02 att/10/12/2012`

The result of attendance in the GUI is still indicated as F instead of showing the date of attendance.

![image.png](https://raw.githubusercontent.com/Jnjy/ped/main/files/977f69ca-96ab-431f-a099-ae9f0dcf4a8b.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Jnjy/ped#2

**Comment by MrTwit99** [comment]
See Issue https://github.com/AY2223S2-CS2103T-T09-1/tp/issues/174 for feature fix for attendance
