### ISSUE TITLE
[PE-D][Tester C] Incorrect command syntax

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T09-1/tp#168]
![Screenshot 2023-03-31 at 2.34.05 PM.jpg](https://raw.githubusercontent.com/jishnu28/ped/main/files/a690caef-4571-468a-ab15-1212387fe061.jpg)

The command prefix needed is `student <CLASS> ` not just `student <CLASS>`. The space is missing at the end

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: jishnu28/ped#2

**Comment by MrTwit99** [comment]
This error is considered irrelevant since example of command usage shows `student <CLASS>` with a space and one would not likely notice the space when mention `student <CLASS>` under the General Student Command.
