### ISSUE TITLE
[PE-D][Tester C] Unclear options for marking students as absent

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T09-1/tp#174]
![Screenshot 2023-03-31 at 2.39.47 PM.jpg](https://raw.githubusercontent.com/jishnu28/ped/main/files/2830fc77-c3c7-47db-bcda-25888d2d00fb.jpg)
No option to mark the student as 'absent'. Or at least it's not explicit in the UG that the default option also denotes 'absent'.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: jishnu28/ped#3

**Comment by MrTwit99** [comment]
Added warnings to warn users and developers in UG and DG on the limitations of attendance feature in this version of PowerConnect and how it would be patched in future releases with even more functionalities.
