### ISSUE TITLE
[PE-D][Tester C] Cumulative tests weightage

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T09-1/tp#181]
![Screenshot 2023-03-31 at 2.46.48 PM.jpg](https://raw.githubusercontent.com/jishnu28/ped/main/files/a3d15ad8-513c-4ad4-a59b-f7fc3d8becd2.jpg)
Product ensures that each test added does not have a weightage over 100% but it is still possible to add multiple tests that together have an overall weightage over 100% which should not be possible

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jishnu28/ped#4

**Comment by MrTwit99** [comment]
To update User Guide informing Users this is an intended BUG that WILL NOT be fixed at this version of PowerConnect!
