### ISSUE TITLE
[PE-D][Tester D] Usage of confusing placeholder

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T09-1/tp#192]
The placeholder used to indicate empty information can be very distracting if use "Insert .... here".

![image.png](https://raw.githubusercontent.com/Jnjy/ped/main/files/88d4fb11-6f47-4a64-8410-b59e4975dc2b.png)

Can try placeholder like "-" which is easier to the eyes.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Jnjy/ped#11

**Comment by MrTwit99** [comment]
Subjective opinion, not necessary required but thanks for the suggestion.
